services:
  frontend:
    container_name: mp4together-frontend
    build:
      context: ../Mp4Together-client
      dockerfile: Dockerfile.dev
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
      - VITE_FRONTEND_URL=localhost:5173
      - VITE_SFU_SERVER_URL=http://localhost:3001
      - VITE_PEERJS_SERVER_URL=localhost
      - VITE_PEERJS_PORT=9000
    env_file:
      - ../Mp4Together-client/.env
    ports:
      - "5173:5173"
    volumes:
      - ../Mp4Together-client/src:/home/node/app/src
  backend:
    container_name: mp4together-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - FRONTEND_URL=http://localhost:5173
      - SFU_SERVER_URL=http://sfu:3001
      - DB_URL=mongodb://mongo:27017/Watch2Gether
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
    depends_on:
      - mongo
      - redis
      - sfu
  mongo:
    container_name: mp4together-mongo
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    volumes:
      - mp4together-mongo-data:/data/db
    restart: on-failure:5
  redis:
    container_name: mp4together-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - mp4together-redis-data:/data
    restart: on-failure:5
  peerjs:
    container_name: mp4together-peerjs-server
    image: peerjs/peerjs-server:1.1.0-rc.2
    ports:
      - "9000:9000"
    restart: on-failure:5
  sfu:
    container_name: mp4together-sfu
    build:
      context: ../Mp4Together-sfu
      dockerfile: Dockerfile.dev
    environment:
      - FRONTEND_URL=http://localhost:5173
      - MAIN_SERVER_URL=http://backend:3000
      - SERVER_ANNOUNCED_IP=${HOST_IP}
      - PORT=3001
    env_file:
      - ../Mp4Together-sfu/.env
    ports:
      - "3001:3001"
      - "10000-10100:10000-10100/tcp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ../Mp4Together-sfu/src:/home/node/app/src
volumes:
  mp4together-mongo-data:
  mp4together-redis-data:
